GET http://localhost:3000/users/videos HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjIxMzY5Nzk5LCJleHAiOjE2MjM5NjE3OTl9.alT4Z5FJg6EkbT6DCBUjQm_fxGZCu-5S99M2BHYkP8s
Content-Type: application/json
